export const SIGN_IN = 'app/SIGN_IN';
export const SIGN_OUT = 'app/SIGN_OUT';
export const AUTHENTICATED = 'app/AUTHENTICATED';
export const AUTHENTICATION_FAILED = 'app/AUTHENTICATION_FAILED';
export const CLEAR_AUTHENTICATION_MESSAGE = 'app/CLEAR_AUTHENTICATION_MESSAGE';
export const REGISTER = 'app/REGISTER';
export const REGISTRATION_FAILED = 'app/REGISTRATION_FAILED';
export const RESET_PASSWORD = 'app/RESET_PASSWORD';
export const RESET_PASSWORD_FAILED = 'app/RESET_PASSWORD_FAILED';

export const OPEN_VIEW = 'app/OPEN_VIEW';
export const OPEN_DYNAMIC_VIEW = 'app/OPEN_DYNAMIC_VIEW';
export const OPENED_VIEW = 'app/OPENED_VIEW';
export const OPENED_DYNAMIC_VIEW = 'app/OPENED_DYNAMIC_VIEW';
export const CLOSE_VIEW = 'app/CLOSE_VIEW';
export const CLOSED_VIEW = 'app/CLOSED_VIEW';
export const SELECT_MENU_ITEM = 'app/SELECT_MENU_ITEM';
export const SELECTED_MENU_ITEM = 'app/SELECTED_MENU_ITEM';

export const OPEN_SETTING_DRAWER = 'app/OPEN_SETTING_DRAWER';
export const CLOSE_SETTING_DRAWER = 'app/CLOSE_SETTING_DRAWER';
export const CHANGE_THEME = 'app/CHANGE_THEME';

export const SHOW_HIDE_OPEN_VIEWS = 'app/SHOW_HIDE_OPEN_VIEWS';
export const SHOW_HIDE_HEADER_TABS = 'app/SHOW_HIDE_HEADER_TABS';

export const SHOW_SEARCH = 'app/SHOW_SEARCH';
